// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetRootData, GetRootResponses, GetRootErrors, GetCompaniesData, GetCompaniesResponses, GetCompaniesErrors, PutCompanyData, PutCompanyResponses, PutCompanyErrors, GetCompanyCategoriesData, GetCompanyCategoriesResponses, GetCompanyCategoriesErrors, GetCompanyData, GetCompanyResponses, GetCompanyErrors, GetFilesData, GetFilesResponses, GetFilesErrors, GetFileBasePathData, GetFileBasePathResponses, GetFileBasePathErrors, BulkConvertIdsData, BulkConvertIdsResponses, BulkConvertIdsErrors, GetIdSyncConfigData, GetIdSyncConfigResponses, GetIdSyncConfigErrors, GenerateKojiIdData, GenerateKojiIdResponses, GenerateKojiIdErrors, GeneratePathIdData, GeneratePathIdResponses, GeneratePathIdErrors, GetIdMappingData, GetIdMappingResponses, GetIdMappingErrors, ValidateIdData, ValidateIdResponses, ValidateIdErrors, GetKojiesData, GetKojiesResponses, GetKojiesErrors, PutKojiData, PutKojiResponses, PutKojiErrors, PutKojiStandardFilesData, PutKojiStandardFilesResponses, PutKojiStandardFilesErrors, GetKojiData, GetKojiResponses, GetKojiErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * API ルート情報取得
 * API のバージョンやドキュメントURLを返します
 */
export const getRoot = <ThrowOnError extends boolean = false>(options?: Options<GetRootData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRootResponses, GetRootErrors, ThrowOnError>({
        url: '/',
        ...options
    });
};

/**
 * 会社一覧の取得
 * 会社フォルダーの一覧を取得します
 */
export const getCompanies = <ThrowOnError extends boolean = false>(options?: Options<GetCompaniesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCompaniesResponses, GetCompaniesErrors, ThrowOnError>({
        url: '/companies',
        ...options
    });
};

/**
 * 会社情報の更新
 * 会社情報を更新し、必要に応じてフォルダー名を変更します
 */
export const putCompany = <ThrowOnError extends boolean = false>(options: Options<PutCompanyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutCompanyResponses, PutCompanyErrors, ThrowOnError>({
        url: '/companies',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * カテゴリー一覧の取得
 * カテゴリー一覧を取得します
 */
export const getCompanyCategories = <ThrowOnError extends boolean = false>(options?: Options<GetCompanyCategoriesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCompanyCategoriesResponses, GetCompanyCategoriesErrors, ThrowOnError>({
        url: '/companies/categories',
        ...options
    });
};

/**
 * 会社詳細の取得
 * 指定されたIDの会社詳細を取得します
 */
export const getCompany = <ThrowOnError extends boolean = false>(options: Options<GetCompanyData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCompanyResponses, GetCompanyErrors, ThrowOnError>({
        url: '/companies/{id}',
        ...options
    });
};

/**
 * ファイルエントリ一覧の取得
 * 指定されたパスからファイルとフォルダーの一覧を取得します
 */
export const getFiles = <ThrowOnError extends boolean = false>(options?: Options<GetFilesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetFilesResponses, GetFilesErrors, ThrowOnError>({
        url: '/files',
        ...options
    });
};

/**
 * ファイルサービスの基準パス取得
 * ファイルサービスが参照する基準パスを返します
 */
export const getFileBasePath = <ThrowOnError extends boolean = false>(options?: Options<GetFileBasePathData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetFileBasePathResponses, GetFileBasePathErrors, ThrowOnError>({
        url: '/files/base-path',
        ...options
    });
};

/**
 * 一括ID変換
 * 複数のアイテムを一括でID変換します
 */
export const bulkConvertIds = <ThrowOnError extends boolean = false>(options: Options<BulkConvertIdsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<BulkConvertIdsResponses, BulkConvertIdsErrors, ThrowOnError>({
        url: '/id-sync/bulk-convert',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 同期設定の取得
 * ID同期システムの設定情報を取得します
 */
export const getIdSyncConfig = <ThrowOnError extends boolean = false>(options?: Options<GetIdSyncConfigData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetIdSyncConfigResponses, GetIdSyncConfigErrors, ThrowOnError>({
        url: '/id-sync/config',
        ...options
    });
};

/**
 * 工事IDの生成
 * 開始日・会社名・場所名から工事IDを生成します
 */
export const generateKojiId = <ThrowOnError extends boolean = false>(options: Options<GenerateKojiIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GenerateKojiIdResponses, GenerateKojiIdErrors, ThrowOnError>({
        url: '/id-sync/generate-koji',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * パスIDの生成
 * フルパスから Len7 ID を生成します
 */
export const generatePathId = <ThrowOnError extends boolean = false>(options: Options<GeneratePathIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<GeneratePathIdResponses, GeneratePathIdErrors, ThrowOnError>({
        url: '/id-sync/generate-path',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * IDマッピングテーブルの取得
 * フルパスIDとLen7 IDのマッピングテーブルを取得します
 */
export const getIdMapping = <ThrowOnError extends boolean = false>(options?: Options<GetIdMappingData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetIdMappingResponses, GetIdMappingErrors, ThrowOnError>({
        url: '/id-sync/mapping',
        ...options
    });
};

/**
 * IDの検証
 * 提供されたIDが正しいかどうかを検証します
 */
export const validateId = <ThrowOnError extends boolean = false>(options: Options<ValidateIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<ValidateIdResponses, ValidateIdErrors, ThrowOnError>({
        url: '/id-sync/validate',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 工事一覧の取得
 * 工事一覧を取得します。filter=recentで最近の工事のみを取得できます
 */
export const getKojies = <ThrowOnError extends boolean = false>(options?: Options<GetKojiesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetKojiesResponses, GetKojiesErrors, ThrowOnError>({
        url: '/kojies',
        ...options
    });
};

/**
 * 工事情報の更新
 * 工事のファイル情報を更新します
 */
export const putKoji = <ThrowOnError extends boolean = false>(options: Options<PutKojiData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutKojiResponses, PutKojiErrors, ThrowOnError>({
        url: '/kojies',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 標準ファイル名の変更
 * StandardFileの名前を変更し、最新の工事データを返します
 */
export const putKojiStandardFiles = <ThrowOnError extends boolean = false>(options: Options<PutKojiStandardFilesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutKojiStandardFilesResponses, PutKojiStandardFilesErrors, ThrowOnError>({
        url: '/kojies/standard-files',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 工事詳細の取得
 * 指定されたフォルダー名の工事を取得します
 */
export const getKoji = <ThrowOnError extends boolean = false>(options: Options<GetKojiData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetKojiResponses, GetKojiErrors, ThrowOnError>({
        url: '/kojies/{path}',
        ...options
    });
};