// This file is auto-generated by @hey-api/openapi-ts

export type BulkConvertIdsRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    Items: Array<Item> | null;
};

export type BulkConvertIdsResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    Results: Array<Item> | null;
    errorCount: number;
    processedAt: string;
    successCount: number;
    totalCount: number;
};

export type Company = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    address?: string;
    category: string;
    email?: string;
    folderName: string;
    id: string;
    legalName?: string;
    phone?: string;
    postalCode?: string;
    requiredFiles: Array<FileInfo> | null;
    shortName?: string;
    tags?: Array<string> | null;
    website?: string;
};

export type CompanyCategoryInfo = {
    code: string;
    label: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type FileInfo = {
    isDirectory: boolean;
    modifiedTime: string;
    size: number;
    standardPath: string;
    targetPath: string;
};

export type GenerateKojiIdRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * 会社名
     */
    companyName: string;
    /**
     * 場所名
     */
    locationName: string;
    /**
     * 開始日 (ISO 8601)
     */
    startDate: string;
};

export type GenerateKojiIdResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: string;
    errorMsg: string;
    id: string;
    idType: string;
    isValid: boolean;
    length: number;
    method: string;
    source: string;
};

export type GeneratePathIdRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * パスID生成用フルパス
     */
    fullPath: string;
};

export type GeneratePathIdResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    created: string;
    errorMsg: string;
    id: string;
    idType: string;
    isValid: boolean;
    length: number;
    method: string;
    source: string;
};

export type GetRootResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    docs: string;
    message: string;
    version: string;
};

export type GetFileBasePathResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * ファイルサービスの基準パス
     */
    basePath: string;
};

export type Item = {
    companyName: string;
    fullPath: string;
    locationName: string;
    startDate: string;
};

export type Koji = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    companyName?: string;
    description?: string;
    endDate: string;
    id: string;
    locationName?: string;
    requiredFiles: Array<FileInfo> | null;
    startDate?: string;
    status?: string;
    tags?: Array<string> | null;
    targetFolder: string;
};

export type PutKojiStandardFilesRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    currents: Array<string> | null;
    koji: Koji;
};

export type ValidateIdRequest = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    companyName: string;
    fullPath: string;
    id: string;
    locationName: string;
    startDate: string;
};

export type ValidateIdResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    comparedAt: string;
    errorMsg: string;
    expectedId: string;
    isValid: boolean;
    method: string;
    needsSync: boolean;
    providedId: string;
};

export type GetRootData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetRootErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetRootError = GetRootErrors[keyof GetRootErrors];

export type GetRootResponses = {
    /**
     * OK
     */
    200: GetRootResponse;
};

export type GetRootResponse2 = GetRootResponses[keyof GetRootResponses];

export type GetCompaniesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/companies';
};

export type GetCompaniesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetCompaniesError = GetCompaniesErrors[keyof GetCompaniesErrors];

export type GetCompaniesResponses = {
    /**
     * 会社一覧
     */
    200: Array<Company> | null;
};

export type GetCompaniesResponse = GetCompaniesResponses[keyof GetCompaniesResponses];

export type PutCompanyData = {
    body: Company;
    path?: never;
    query?: never;
    url: '/companies';
};

export type PutCompanyErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PutCompanyError = PutCompanyErrors[keyof PutCompanyErrors];

export type PutCompanyResponses = {
    /**
     * OK
     */
    200: Company;
};

export type PutCompanyResponse = PutCompanyResponses[keyof PutCompanyResponses];

export type GetCompanyCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/companies/categories';
};

export type GetCompanyCategoriesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetCompanyCategoriesError = GetCompanyCategoriesErrors[keyof GetCompanyCategoriesErrors];

export type GetCompanyCategoriesResponses = {
    /**
     * カテゴリー一覧
     */
    200: Array<CompanyCategoryInfo> | null;
};

export type GetCompanyCategoriesResponse = GetCompanyCategoriesResponses[keyof GetCompanyCategoriesResponses];

export type GetCompanyData = {
    body?: never;
    path: {
        /**
         * 会社ID
         */
        id: string;
    };
    query?: never;
    url: '/companies/{id}';
};

export type GetCompanyErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetCompanyError = GetCompanyErrors[keyof GetCompanyErrors];

export type GetCompanyResponses = {
    /**
     * 会社詳細
     */
    200: Company;
};

export type GetCompanyResponse = GetCompanyResponses[keyof GetCompanyResponses];

export type GetFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 取得するディレクトリの相対パス
         */
        path?: string;
    };
    url: '/files';
};

export type GetFilesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetFilesError = GetFilesErrors[keyof GetFilesErrors];

export type GetFilesResponses = {
    /**
     * ファイルエントリ一覧
     */
    200: Array<FileInfo> | null;
};

export type GetFilesResponse = GetFilesResponses[keyof GetFilesResponses];

export type GetFileBasePathData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/files/base-path';
};

export type GetFileBasePathErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetFileBasePathError = GetFileBasePathErrors[keyof GetFileBasePathErrors];

export type GetFileBasePathResponses = {
    /**
     * OK
     */
    200: GetFileBasePathResponseBody;
};

export type GetFileBasePathResponse = GetFileBasePathResponses[keyof GetFileBasePathResponses];

export type BulkConvertIdsData = {
    body: BulkConvertIdsRequest;
    path?: never;
    query?: never;
    url: '/id-sync/bulk-convert';
};

export type BulkConvertIdsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type BulkConvertIdsError = BulkConvertIdsErrors[keyof BulkConvertIdsErrors];

export type BulkConvertIdsResponses = {
    /**
     * OK
     */
    200: BulkConvertIdsResponse;
};

export type BulkConvertIdsResponse2 = BulkConvertIdsResponses[keyof BulkConvertIdsResponses];

export type GetIdSyncConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/id-sync/config';
};

export type GetIdSyncConfigErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetIdSyncConfigError = GetIdSyncConfigErrors[keyof GetIdSyncConfigErrors];

export type GetIdSyncConfigResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetIdSyncConfigResponse = GetIdSyncConfigResponses[keyof GetIdSyncConfigResponses];

export type GenerateKojiIdData = {
    body: GenerateKojiIdRequest;
    path?: never;
    query?: never;
    url: '/id-sync/generate-koji';
};

export type GenerateKojiIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GenerateKojiIdError = GenerateKojiIdErrors[keyof GenerateKojiIdErrors];

export type GenerateKojiIdResponses = {
    /**
     * OK
     */
    200: GenerateKojiIdResponse;
};

export type GenerateKojiIdResponse2 = GenerateKojiIdResponses[keyof GenerateKojiIdResponses];

export type GeneratePathIdData = {
    body: GeneratePathIdRequest;
    path?: never;
    query?: never;
    url: '/id-sync/generate-path';
};

export type GeneratePathIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GeneratePathIdError = GeneratePathIdErrors[keyof GeneratePathIdErrors];

export type GeneratePathIdResponses = {
    /**
     * OK
     */
    200: GeneratePathIdResponse;
};

export type GeneratePathIdResponse2 = GeneratePathIdResponses[keyof GeneratePathIdResponses];

export type GetIdMappingData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * カンマ区切りのパスリスト
         */
        paths?: string;
    };
    url: '/id-sync/mapping';
};

export type GetIdMappingErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetIdMappingError = GetIdMappingErrors[keyof GetIdMappingErrors];

export type GetIdMappingResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type GetIdMappingResponse = GetIdMappingResponses[keyof GetIdMappingResponses];

export type ValidateIdData = {
    body: ValidateIdRequest;
    path?: never;
    query?: never;
    url: '/id-sync/validate';
};

export type ValidateIdErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ValidateIdError = ValidateIdErrors[keyof ValidateIdErrors];

export type ValidateIdResponses = {
    /**
     * OK
     */
    200: ValidateIdResponse;
};

export type ValidateIdResponse2 = ValidateIdResponses[keyof ValidateIdResponses];

export type GetKojiesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * フィルター (recent: 最近の工事のみ)
         */
        filter?: string;
    };
    url: '/kojies';
};

export type GetKojiesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetKojiesError = GetKojiesErrors[keyof GetKojiesErrors];

export type GetKojiesResponses = {
    /**
     * 工事一覧
     */
    200: Array<Koji> | null;
};

export type GetKojiesResponse = GetKojiesResponses[keyof GetKojiesResponses];

export type PutKojiData = {
    body: Koji;
    path?: never;
    query?: never;
    url: '/kojies';
};

export type PutKojiErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PutKojiError = PutKojiErrors[keyof PutKojiErrors];

export type PutKojiResponses = {
    /**
     * OK
     */
    200: Koji;
};

export type PutKojiResponse = PutKojiResponses[keyof PutKojiResponses];

export type PutKojiStandardFilesData = {
    body: PutKojiStandardFilesRequestBody;
    path?: never;
    query?: never;
    url: '/kojies/standard-files';
};

export type PutKojiStandardFilesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PutKojiStandardFilesError = PutKojiStandardFilesErrors[keyof PutKojiStandardFilesErrors];

export type PutKojiStandardFilesResponses = {
    /**
     * 更新後の工事データ
     */
    200: unknown;
};

export type GetKojiData = {
    body?: never;
    path: {
        /**
         * Kojiフォルダー名
         */
        path: string;
    };
    query?: never;
    url: '/kojies/{path}';
};

export type GetKojiErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetKojiError = GetKojiErrors[keyof GetKojiErrors];

export type GetKojiResponses = {
    /**
     * 工事詳細
     */
    200: Koji;
};

export type GetKojiResponse = GetKojiResponses[keyof GetKojiResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api' | 'https://localhost:8443/api' | (string & {});
};