// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/kouji": {
    params: {};
  };
  "/gantt": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/kouji" | "/gantt";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/kouji" | "/gantt";
  };
  "routes/_layout._index.tsx": {
    id: "routes/_layout._index";
    page: "/";
  };
  "routes/_layout.kouji.tsx": {
    id: "routes/_layout.kouji";
    page: "/kouji";
  };
  "routes/_layout.gantt.tsx": {
    id: "routes/_layout.gantt";
    page: "/gantt";
  };
};