// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/files": {
    params: {};
  };
  "/kojies": {
    params: {};
  };
  "/kojies/gantt": {
    params: {};
  };
  "/companies": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/files" | "/kojies" | "/kojies/gantt" | "/companies";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/files" | "/kojies" | "/kojies/gantt" | "/companies";
  };
  "routes/_layout._index.tsx": {
    id: "routes/_layout._index";
    page: "/";
  };
  "routes/_layout.files.tsx": {
    id: "routes/_layout.files";
    page: "/files";
  };
  "routes/_layout.kojies.tsx": {
    id: "routes/_layout.kojies";
    page: "/kojies";
  };
  "routes/_layout.gantt.tsx": {
    id: "routes/_layout.gantt";
    page: "/kojies/gantt";
  };
  "routes/_layout.companies.tsx": {
    id: "routes/_layout.companies";
    page: "/companies";
  };
};