// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/projects": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/projects";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/" | "/projects";
  };
  "routes/_layout._index.tsx": {
    id: "routes/_layout._index";
    page: "/";
  };
  "routes/_layout.projects.tsx": {
    id: "routes/_layout.projects";
    page: "/projects";
  };
};