// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/file/fileinfos": {
            "get": {
                "description": "指定されたパスからファイルとフォルダーの一覧を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ファイル管理"
                ],
                "summary": "ファイルエントリ一覧の取得",
                "parameters": [
                    {
                        "type": "string",
                        "default": "~/penguin",
                        "description": "取得するディレクトリのパス",
                        "name": "path",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "正常なレスポンス",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.FileInfo"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/project/get/{path}": {
            "get": {
                "description": "Projectを取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "プロジェクト管理"
                ],
                "summary": "Projectの取得",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Projectフォルダーのファイル名",
                        "name": "path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Project",
                        "schema": {
                            "$ref": "#/definitions/models.Project"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/project/recent": {
            "get": {
                "description": "最近の工事一覧を取得します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "プロジェクト管理"
                ],
                "summary": "最近の工事一覧の取得",
                "responses": {
                    "200": {
                        "description": "最近のプロジェクト一覧",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Project"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/project/rename-managed-file": {
            "post": {
                "description": "ManagedFileの名前を変更します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "プロジェクト管理"
                ],
                "summary": "ManagedFileの名前を変更",
                "parameters": [
                    {
                        "description": "工事データと管理ファイル",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handlers.RenameManagedFileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新後のファイル名リスト",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/project/update": {
            "post": {
                "description": "Project.FileInfoで指定されたファイル情報をProjectのメンバ変数で更新します。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "プロジェクト管理"
                ],
                "summary": "Project.FileInfoで指定されたファイル情報をProjectのメンバ変数で更新",
                "parameters": [
                    {
                        "description": "工事データ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Project"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新後の工事データ",
                        "schema": {
                            "$ref": "#/definitions/models.Project"
                        }
                    },
                    "500": {
                        "description": "サーバーエラー",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.RenameManagedFileRequest": {
            "type": "object",
            "properties": {
                "currents": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "project": {
                    "$ref": "#/definitions/models.Project"
                }
            }
        },
        "models.FileInfo": {
            "description": "ファイルまたはディレクトリの情報",
            "type": "object",
            "properties": {
                "is_directory": {
                    "description": "Whether this item is a directory",
                    "type": "boolean",
                    "example": true
                },
                "modified_time": {
                    "description": "Last modification time",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Timestamp"
                        }
                    ]
                },
                "name": {
                    "description": "Name of the file or folder",
                    "type": "string",
                    "example": "2025-0618 豊田築炉 名和工場"
                },
                "path": {
                    "description": "FileService.BasePathからの相対パス",
                    "type": "string",
                    "example": "豊田築炉/2-工事/2025-0618 豊田築炉 名和工場"
                },
                "size": {
                    "description": "Size of the file in bytes",
                    "type": "integer",
                    "example": 4096
                }
            }
        },
        "models.ManagedFile": {
            "type": "object",
            "properties": {
                "current": {
                    "description": "FileService.BasePathからの相対パス",
                    "type": "string",
                    "example": "工事.xlsx"
                },
                "recommended": {
                    "description": "FileService.BasePathからの相対パス",
                    "type": "string",
                    "example": "2025-0618 豊田築炉 名和工場.xlsx"
                }
            }
        },
        "models.Project": {
            "description": "Construction project folder information with extended attributes",
            "type": "object",
            "properties": {
                "company_name": {
                    "description": "Additional fields specific to Project folders",
                    "type": "string",
                    "example": "豊田築炉"
                },
                "description": {
                    "type": "string",
                    "example": "工事関連の資料とドキュメント"
                },
                "end_date": {
                    "description": "Detail",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Timestamp"
                        }
                    ]
                },
                "id": {
                    "description": "Calculated fields",
                    "type": "string",
                    "example": "TC618"
                },
                "is_directory": {
                    "description": "Whether this item is a directory",
                    "type": "boolean",
                    "example": true
                },
                "location_name": {
                    "type": "string",
                    "example": "名和工場"
                },
                "managed_files": {
                    "description": "Managed files",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ManagedFile"
                    }
                },
                "modified_time": {
                    "description": "Last modification time",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Timestamp"
                        }
                    ]
                },
                "name": {
                    "description": "Name of the file or folder",
                    "type": "string",
                    "example": "2025-0618 豊田築炉 名和工場"
                },
                "path": {
                    "description": "FileService.BasePathからの相対パス",
                    "type": "string",
                    "example": "豊田築炉/2-工事/2025-0618 豊田築炉 名和工場"
                },
                "size": {
                    "description": "Size of the file in bytes",
                    "type": "integer",
                    "example": 4096
                },
                "start_date": {
                    "$ref": "#/definitions/models.Timestamp"
                },
                "status": {
                    "type": "string",
                    "example": "進行中"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "['工事'",
                        " '豊田築炉'",
                        " '名和工場']"
                    ]
                }
            }
        },
        "models.Timestamp": {
            "description": "Timestamp in RFC3339 format",
            "type": "object",
            "properties": {
                "time.Time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{"http"},
	Title:            "Penguin ファイルシステム管理API",
	Description:      "ファイルエントリの管理と閲覧のためのAPI",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
