// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetFileFileinfosData, GetFileFileinfosResponses, GetFileFileinfosErrors, GetProjectRecentData, GetProjectRecentResponses, GetProjectRecentErrors, PostProjectUpdateData, PostProjectUpdateResponses, PostProjectUpdateErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * ファイルエントリ一覧の取得
 * 指定されたパスからファイルとフォルダーの一覧を取得します
 */
export const getFileFileinfos = <ThrowOnError extends boolean = false>(options?: Options<GetFileFileinfosData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetFileFileinfosResponses, GetFileFileinfosErrors, ThrowOnError>({
        url: '/file/fileinfos',
        ...options
    });
};

/**
 * 最近の工事一覧の取得
 * 最近の工事一覧を取得します。
 */
export const getProjectRecent = <ThrowOnError extends boolean = false>(options?: Options<GetProjectRecentData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetProjectRecentResponses, GetProjectRecentErrors, ThrowOnError>({
        url: '/project/recent',
        ...options
    });
};

/**
 * 指定されたプロジェクト情報のYAML保存
 * models.ProjectをYAMLファイルに保存します
 */
export const postProjectUpdate = <ThrowOnError extends boolean = false>(options: Options<PostProjectUpdateData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostProjectUpdateResponses, PostProjectUpdateErrors, ThrowOnError>({
        url: '/project/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};