// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { GetCompaniesData, GetCompaniesResponses, GetCompaniesErrors, PutCompaniesData, PutCompaniesResponses, PutCompaniesErrors, GetCompaniesByIdData, GetCompaniesByIdResponses, GetCompaniesByIdErrors, GetFilesData, GetFilesResponses, GetFilesErrors, GetKojiesData, GetKojiesResponses, GetKojiesErrors, PutKojiesData, PutKojiesResponses, PutKojiesErrors, GetKojiesByPathData, GetKojiesByPathResponses, GetKojiesByPathErrors, PutKojiesManagedFilesData, PutKojiesManagedFilesResponses, PutKojiesManagedFilesErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * 会社一覧の取得
 * 会社フォルダーの一覧を取得します
 */
export const getCompanies = <ThrowOnError extends boolean = false>(options?: Options<GetCompaniesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetCompaniesResponses, GetCompaniesErrors, ThrowOnError>({
        url: '/companies',
        ...options
    });
};

/**
 * 会社情報の更新
 * 会社情報を更新し、必要に応じてフォルダー名を変更します
 */
export const putCompanies = <ThrowOnError extends boolean = false>(options: Options<PutCompaniesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutCompaniesResponses, PutCompaniesErrors, ThrowOnError>({
        url: '/companies',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * 会社詳細の取得
 * 指定されたIDの会社詳細を取得します
 */
export const getCompaniesById = <ThrowOnError extends boolean = false>(options: Options<GetCompaniesByIdData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetCompaniesByIdResponses, GetCompaniesByIdErrors, ThrowOnError>({
        url: '/companies/{id}',
        ...options
    });
};

/**
 * ファイルエントリ一覧の取得
 * 指定されたパスからファイルとフォルダーの一覧を取得します
 */
export const getFiles = <ThrowOnError extends boolean = false>(options?: Options<GetFilesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetFilesResponses, GetFilesErrors, ThrowOnError>({
        url: '/files',
        ...options
    });
};

/**
 * 工事一覧の取得
 * 工事一覧を取得します。filter=recentで最近の工事のみを取得できます。
 */
export const getKojies = <ThrowOnError extends boolean = false>(options?: Options<GetKojiesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetKojiesResponses, GetKojiesErrors, ThrowOnError>({
        url: '/kojies',
        ...options
    });
};

/**
 * 更新対象フォルダー（Koji.FileInfo）のファイル情報をKojiのメンバ変数で更新
 * 更新対象フォルダー（Koji.FileInfo）のファイル情報をKojiのメンバ変数で更新します。
 */
export const putKojies = <ThrowOnError extends boolean = false>(options: Options<PutKojiesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutKojiesResponses, PutKojiesErrors, ThrowOnError>({
        url: '/kojies',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Kojiの取得
 * Kojiを取得します。
 */
export const getKojiesByPath = <ThrowOnError extends boolean = false>(options: Options<GetKojiesByPathData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetKojiesByPathResponses, GetKojiesByPathErrors, ThrowOnError>({
        url: '/kojies/{path}',
        ...options
    });
};

/**
 * ManagedFileの名前を変更
 * ManagedFileの名前を変更します。
 */
export const putKojiesManagedFiles = <ThrowOnError extends boolean = false>(options: Options<PutKojiesManagedFilesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<PutKojiesManagedFilesResponses, PutKojiesManagedFilesErrors, ThrowOnError>({
        url: '/kojies/managed-files',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};