// This file is auto-generated by @hey-api/openapi-ts

export type HandlersRenameManagedFileRequest = {
    currents?: Array<string>;
    koji?: ModelsKoji;
};

/**
 * 工事会社の基本情報をファイル名から取得したモデル
 */
export type ModelsCompany = {
    address?: string;
    business_type?: string;
    email?: string;
    /**
     * 属性ファイルフィールド
     */
    full_name?: string;
    /**
     * 計算フィールド
     */
    id?: string;
    /**
     * Whether this item is a directory
     */
    is_directory?: boolean;
    modified_time?: ModelsTimestamp;
    /**
     * Name of the file or folder
     */
    name?: string;
    /**
     * FileService.BasePathからの相対パス
     */
    path?: string;
    phone?: string;
    postal_code?: string;
    /**
     * パス名からの固有フィールド
     */
    short_name?: string;
    /**
     * Size of the file in bytes
     */
    size?: number;
    tags?: Array<string>;
    website?: string;
};

/**
 * ファイルまたはディレクトリの情報
 */
export type ModelsFileInfo = {
    /**
     * Whether this item is a directory
     */
    is_directory?: boolean;
    modified_time?: ModelsTimestamp;
    /**
     * Name of the file or folder
     */
    name?: string;
    /**
     * FileService.BasePathからの相対パス
     */
    path?: string;
    /**
     * Size of the file in bytes
     */
    size?: number;
};

/**
 * 拡張属性を持つ工事プロジェクトフォルダー情報
 */
export type ModelsKoji = {
    /**
     * パス名からの固有フィールド
     */
    company_name?: string;
    description?: string;
    end_date?: ModelsTimestamp;
    /**
     * 計算フィールド
     */
    id?: string;
    /**
     * Whether this item is a directory
     */
    is_directory?: boolean;
    location_name?: string;
    managed_files?: Array<ModelsManagedFile>;
    modified_time?: ModelsTimestamp;
    /**
     * Name of the file or folder
     */
    name?: string;
    /**
     * FileService.BasePathからの相対パス
     */
    path?: string;
    /**
     * Size of the file in bytes
     */
    size?: number;
    start_date?: ModelsTimestamp;
    status?: string;
    tags?: Array<string>;
};

export type ModelsManagedFile = {
    /**
     * FileService.BasePathからの相対パス
     */
    current?: string;
    /**
     * FileService.BasePathからの相対パス
     */
    recommended?: string;
};

/**
 * 属性ファイルフィールド
 */
export type ModelsTimestamp = {
    'time.Time'?: string;
};

export type GetCompaniesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/companies';
};

export type GetCompaniesErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type GetCompaniesError = GetCompaniesErrors[keyof GetCompaniesErrors];

export type GetCompaniesResponses = {
    /**
     * 正常なレスポンス
     */
    200: Array<ModelsCompany>;
};

export type GetCompaniesResponse = GetCompaniesResponses[keyof GetCompaniesResponses];

export type PutCompaniesData = {
    /**
     * 会社データ
     */
    body: ModelsCompany;
    path?: never;
    query?: never;
    url: '/companies';
};

export type PutCompaniesErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type PutCompaniesError = PutCompaniesErrors[keyof PutCompaniesErrors];

export type PutCompaniesResponses = {
    /**
     * 更新後の会社データ
     */
    200: ModelsCompany;
};

export type PutCompaniesResponse = PutCompaniesResponses[keyof PutCompaniesResponses];

export type GetCompaniesByIdData = {
    body?: never;
    path: {
        /**
         * 会社ID
         */
        id: string;
    };
    query?: never;
    url: '/companies/{id}';
};

export type GetCompaniesByIdErrors = {
    /**
     * 会社が見つからない
     */
    404: {
        [key: string]: string;
    };
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type GetCompaniesByIdError = GetCompaniesByIdErrors[keyof GetCompaniesByIdErrors];

export type GetCompaniesByIdResponses = {
    /**
     * 正常なレスポンス
     */
    200: ModelsCompany;
};

export type GetCompaniesByIdResponse = GetCompaniesByIdResponses[keyof GetCompaniesByIdResponses];

export type GetFilesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 取得するディレクトリのパス
         */
        path?: string;
    };
    url: '/files';
};

export type GetFilesErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type GetFilesError = GetFilesErrors[keyof GetFilesErrors];

export type GetFilesResponses = {
    /**
     * 正常なレスポンス
     */
    200: Array<ModelsFileInfo>;
};

export type GetFilesResponse = GetFilesResponses[keyof GetFilesResponses];

export type GetKojiesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * フィルター (recent: 最近の工事のみ)
         */
        filter?: string;
    };
    url: '/kojies';
};

export type GetKojiesErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type GetKojiesError = GetKojiesErrors[keyof GetKojiesErrors];

export type GetKojiesResponses = {
    /**
     * 工事一覧
     */
    200: Array<ModelsKoji>;
};

export type GetKojiesResponse = GetKojiesResponses[keyof GetKojiesResponses];

export type PutKojiesData = {
    /**
     * 工事データ
     */
    body: ModelsKoji;
    path?: never;
    query?: never;
    url: '/kojies';
};

export type PutKojiesErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type PutKojiesError = PutKojiesErrors[keyof PutKojiesErrors];

export type PutKojiesResponses = {
    /**
     * 更新後の工事データ
     */
    200: ModelsKoji;
};

export type PutKojiesResponse = PutKojiesResponses[keyof PutKojiesResponses];

export type GetKojiesByPathData = {
    body?: never;
    path: {
        /**
         * Kojiフォルダーのファイル名
         */
        path: string;
    };
    query?: never;
    url: '/kojies/{path}';
};

export type GetKojiesByPathErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type GetKojiesByPathError = GetKojiesByPathErrors[keyof GetKojiesByPathErrors];

export type GetKojiesByPathResponses = {
    /**
     * Koji
     */
    200: ModelsKoji;
};

export type GetKojiesByPathResponse = GetKojiesByPathResponses[keyof GetKojiesByPathResponses];

export type PutKojiesManagedFilesData = {
    /**
     * 工事データと管理ファイル
     */
    body: HandlersRenameManagedFileRequest;
    path?: never;
    query?: never;
    url: '/kojies/managed-files';
};

export type PutKojiesManagedFilesErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type PutKojiesManagedFilesError = PutKojiesManagedFilesErrors[keyof PutKojiesManagedFilesErrors];

export type PutKojiesManagedFilesResponses = {
    /**
     * 更新後のファイル名リスト
     */
    200: Array<string>;
};

export type PutKojiesManagedFilesResponse = PutKojiesManagedFilesResponses[keyof PutKojiesManagedFilesResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api' | (string & {});
};