// This file is auto-generated by @hey-api/openapi-ts

export type HandlersRenameManagedFileRequest = {
    currents?: Array<string>;
    project?: ModelsProject;
};

/**
 * ファイルまたはディレクトリの情報
 */
export type ModelsFileInfo = {
    /**
     * Whether this item is a directory
     */
    is_directory?: boolean;
    /**
     * Last modification time
     */
    modified_time?: ModelsTimestamp;
    /**
     * Name of the file or folder
     */
    name?: string;
    /**
     * FileService.BasePathからの相対パス
     */
    path?: string;
    /**
     * Size of the file in bytes
     */
    size?: number;
};

export type ModelsManagedFile = {
    /**
     * FileService.BasePathからの相対パス
     */
    current?: string;
    /**
     * FileService.BasePathからの相対パス
     */
    recommended?: string;
};

/**
 * 拡張属性を持つ工事プロジェクトフォルダー情報
 */
export type ModelsProject = {
    /**
     * パス名からの固有フィールド
     */
    company_name?: string;
    description?: string;
    /**
     * 属性ファイルフィールド
     */
    end_date?: ModelsTimestamp;
    /**
     * 計算フィールド
     */
    id?: string;
    /**
     * Whether this item is a directory
     */
    is_directory?: boolean;
    location_name?: string;
    managed_files?: Array<ModelsManagedFile>;
    /**
     * Last modification time
     */
    modified_time?: ModelsTimestamp;
    /**
     * Name of the file or folder
     */
    name?: string;
    /**
     * FileService.BasePathからの相対パス
     */
    path?: string;
    /**
     * Size of the file in bytes
     */
    size?: number;
    start_date?: ModelsTimestamp;
    status?: string;
    tags?: Array<string>;
};

/**
 * Timestamp in RFC3339 format
 */
export type ModelsTimestamp = {
    'time.Time'?: string;
};

export type GetFileFileinfosData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * 取得するディレクトリのパス
         */
        path?: string;
    };
    url: '/file/fileinfos';
};

export type GetFileFileinfosErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type GetFileFileinfosError = GetFileFileinfosErrors[keyof GetFileFileinfosErrors];

export type GetFileFileinfosResponses = {
    /**
     * 正常なレスポンス
     */
    200: Array<ModelsFileInfo>;
};

export type GetFileFileinfosResponse = GetFileFileinfosResponses[keyof GetFileFileinfosResponses];

export type GetProjectGetByPathData = {
    body?: never;
    path: {
        /**
         * Projectフォルダーのファイル名
         */
        path: string;
    };
    query?: never;
    url: '/project/get/{path}';
};

export type GetProjectGetByPathErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type GetProjectGetByPathError = GetProjectGetByPathErrors[keyof GetProjectGetByPathErrors];

export type GetProjectGetByPathResponses = {
    /**
     * Project
     */
    200: ModelsProject;
};

export type GetProjectGetByPathResponse = GetProjectGetByPathResponses[keyof GetProjectGetByPathResponses];

export type GetProjectRecentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/project/recent';
};

export type GetProjectRecentErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type GetProjectRecentError = GetProjectRecentErrors[keyof GetProjectRecentErrors];

export type GetProjectRecentResponses = {
    /**
     * 最近のプロジェクト一覧
     */
    200: Array<ModelsProject>;
};

export type GetProjectRecentResponse = GetProjectRecentResponses[keyof GetProjectRecentResponses];

export type PostProjectRenameManagedFileData = {
    /**
     * 工事データと管理ファイル
     */
    body: HandlersRenameManagedFileRequest;
    path?: never;
    query?: never;
    url: '/project/rename-managed-file';
};

export type PostProjectRenameManagedFileErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type PostProjectRenameManagedFileError = PostProjectRenameManagedFileErrors[keyof PostProjectRenameManagedFileErrors];

export type PostProjectRenameManagedFileResponses = {
    /**
     * 更新後のファイル名リスト
     */
    200: Array<string>;
};

export type PostProjectRenameManagedFileResponse = PostProjectRenameManagedFileResponses[keyof PostProjectRenameManagedFileResponses];

export type PostProjectUpdateData = {
    /**
     * 工事データ
     */
    body: ModelsProject;
    path?: never;
    query?: never;
    url: '/project/update';
};

export type PostProjectUpdateErrors = {
    /**
     * サーバーエラー
     */
    500: {
        [key: string]: string;
    };
};

export type PostProjectUpdateError = PostProjectUpdateErrors[keyof PostProjectUpdateErrors];

export type PostProjectUpdateResponses = {
    /**
     * 更新後の工事データ
     */
    200: ModelsProject;
};

export type PostProjectUpdateResponse = PostProjectUpdateResponses[keyof PostProjectUpdateResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:8080/api' | (string & {});
};